<?php

namespace App\Http\Controllers\TestDummy;

use App\Http\Controllers\Controller;
use App\Models\Video;
use App\Models\VisitVideo;
use App\Models\CartVideo;
use App\Models\OrderItemsVideo;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class VideosController extends Controller
{
    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function show($id, $slug = null)
    {

        $array = explode('-', $id);

        if (!(isset($array[1]) && is_numeric($array[1]))) {
            abort(404);
        }


        $id = $array[1];



        header("Cache-Control: no-cache, must-revalidate"); //HTTP 1.1
        header("Pragma: no-cache"); //HTTP 1.0
        header("Expires: Sat, 26 Jul 1997 05:00:00 GMT"); // Date in the past
        $lang = app()->getLocale();
        $user_id = 0;
        if (\Auth::check()) {
            $user_id = \Auth::id();
        }


        $response = Video::with('category')
            ->where('videos.video_fail', 0)
            ->where('status', 'active')->select('videos.*')
            ->leftJoin('collection_video', 'collection_video.video_id', '=', 'videos.id')
            ->leftJoin('collections', 'collection_video.collection_id', '=', 'collections.id')
            ->whereRaw('(( collections.type="public" and videos.user_id != ' . $user_id . ') or (videos.user_id = ' . $user_id . ') or (videos.id not in (select video_id from collection_video)) or (videos.id  in (select video_id from video_downloads)))')
            ->where('videos.id', $id)
            ->whereNull('videos.parent_id')
            ->firstOrFail();


        $response_tag = VideoTag::where('local',$lang)->where('video_id', $response->id)->pluck('tag');

        $tags = [];
        if ($response_tag->count() > 0) {
            $tags = array_chunk($response_tag->all(), ceil($response_tag->count() / 2));
        }

         $simler_images = collect(json_decode('

 [
{
"id": 395,
"sort": 7535,
"parent_id": null,
"thumbnail": "/uploads/videos/395/thumbnail_dwetha2dbI8jjT7MtNUl.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/395/thumbnail_QmUnzPGn9k1Aa5qIWfzg.mp4",
"gif_video": "/uploads/videos/395/thumbnail_CntoX012AIA2VP7FcCob.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/395/240p_Up3m3tbA833Kcbu19tD3.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 90,
"preview": "/uploads/videos/395/uRj8VsmjNHJZKR49LEtu.mp4",
"title_ar": "أسرة  سعودية صغيرة سعيدة تجلس على الأريكة في المنزل , أسرة خليجية يتحدثان في صالة المعيشة في المنزل ",
"title_en": "A happy little Saudi family sitting on the sofa at home, a Gulf family discussing the living room at home",
"type": "FHD",
"duration": "00:13",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 17:11:05",
"status": "active",
"token_id": "AlJ6PvgBXaczrICCXe080EzMRfQ1FvpR4R1QgkCzdtiaQGnyCOASpKKin6uY1On0qXgKl20jPniYHry5yv8P5rQzdNPChxnJxhTLELqQChU1oxwKosBCY3xSa4ej8JSCeQ2zQzvG4YaNv56VNUN0u8Cg0dnWeHvkHQvwvbAuDYXwEnlpbmfK8LR7Vyur1r2fbLpPqYQc",
"extension": "mp4",
"size": "62222905",
"width": "1920",
"height": "1080",
"aspect_ratio": "0:1",
"fps": 25,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "8f52eeeb2d7b0a4c672c594484b4a7e1",
"attribution_required": null,
"original_name": "01",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 1,
"tags": null,
"title": "أسرة  سعودية صغيرة سعيدة تجلس على الأريكة في المنزل , أسرة خليجية يتحدثان في صالة المعيشة في المنزل ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/395/thumbnail_dwetha2dbI8jjT7MtNUl.png",
"is_like": 0,
"str_slug": "a-happy-little-saudi-family-sitting-on-the-sofa-at-home-a-gulf-family-discussing-the-living-room-at-home",
"post_link": "http://www.stock.com/ar/video/395/a-happy-little-saudi-family-sitting-on-the-sofa-at-home-a-gulf-family-discussing-the-living-room-at-home",
"parent": null
},
{
"id": 646,
"sort": 3117,
"parent_id": null,
"thumbnail": "/uploads/videos/646/thumbnail_orczsEIDih5iepnQXnKK.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/646/thumbnail_eaTNVPoWflaoFrWUTTj6.mp4",
"gif_video": "/uploads/videos/646/thumbnail_Pfv5ALLfyg39u709kf04.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/646/240p_eZ2nwqda6er6gmz52NJe.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/646/ORi8OjxYKxAi51hRrmcH.mp4",
"title_ar": "فتاة سعودية صغيرة تشير إلى شيء على واجهة المتجر , عائلة سعودية تنظر إلى واجهة المتجر في المول ",
"title_en": "A little Saudi girl points to something on the storefront, a Saudi family looks at the storefront in the mall",
"type": "4K",
"duration": "00:06",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:09:46",
"status": "active",
"token_id": "4HC7paBboYB1Wy2nZNhshTO28KAyQgYzjBG8SsifzA9NBif81nlOGNg0nlU5UNQ5L0QgVAXThLoZSvZZV05dXulrLILPNCKZnnYcpwCI28dBJHagcqhaFrpI9G1i7Hol7QDzUKQLS2cEnYIBJ3Ujl1NcTekGqgN6fpThVHXZplPSolvGLjHBtnAlTiFhk9hkCvbnkZlP",
"extension": "mp4",
"size": "10645635",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "c24c477f9df4b99ba69499eec068bf1b",
"attribution_required": null,
"original_name": "07",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "فتاة سعودية صغيرة تشير إلى شيء على واجهة المتجر , عائلة سعودية تنظر إلى واجهة المتجر في المول ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/646/thumbnail_orczsEIDih5iepnQXnKK.png",
"is_like": 0,
"str_slug": "a-little-saudi-girl-points-to-something-on-the-storefront-a-saudi-family-looks-at-the-storefront-in-the-mall",
"post_link": "http://www.stock.com/ar/video/646/a-little-saudi-girl-points-to-something-on-the-storefront-a-saudi-family-looks-at-the-storefront-in-the-mall",
"parent": null
},
{
"id": 648,
"sort": 3500,
"parent_id": null,
"thumbnail": "/uploads/videos/648/thumbnail_VxWt8X1jsTLDZZoPUOzI.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/648/thumbnail_YfxrwsS9Izuz6lJvs3Ce.mp4",
"gif_video": "/uploads/videos/648/thumbnail_5BJpoiLmy6vJ3VbiQ2dN.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/648/240p_GfgzV2eX2LJcCKUpcm56.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/648/88eorO6KcmWdqvYNBS3P.mp4",
"title_ar": "فتاة سعودية صغيرة تشير إلى شيء على واجهة المتجر , عائلة سعودية تنظر إلى واجهة المتجر في المول ",
"title_en": "A little Saudi girl points to something on the storefront, a Saudi family looks at the storefront in the mall",
"type": "4K",
"duration": "00:08",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:09:54",
"status": "active",
"token_id": "4UAILlsaxxd8JDBOOCDimjcmRIc2oppsPbDKLoS4G20mNgzvFBXPw40nFiPOCeRmCZbmT7rEOErHQc7g6JHtkzQQfs92oiflrpZNOZQZ7ln77YWxBVk18pQGAViqsWw8BEixWtoyNPQBlu4CBBABhQjGQHxOfpJw7rB0u7XGvGFCuQcrWchyP5ELl36rv9gSIZ8hXfZz",
"extension": "mp4",
"size": "13473824",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "723e1097950cce2fa4db2a82f0629754",
"attribution_required": null,
"original_name": "06",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "فتاة سعودية صغيرة تشير إلى شيء على واجهة المتجر , عائلة سعودية تنظر إلى واجهة المتجر في المول ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/648/thumbnail_VxWt8X1jsTLDZZoPUOzI.png",
"is_like": 0,
"str_slug": "a-little-saudi-girl-points-to-something-on-the-storefront-a-saudi-family-looks-at-the-storefront-in-the-mall",
"post_link": "http://www.stock.com/ar/video/648/a-little-saudi-girl-points-to-something-on-the-storefront-a-saudi-family-looks-at-the-storefront-in-the-mall",
"parent": null
},
{
"id": 653,
"sort": 10108,
"parent_id": null,
"thumbnail": "/uploads/videos/653/thumbnail_2Z8Eh6EPL7hWum7HBMzh.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/653/thumbnail_UpqKl23emPZyXXsLUa7c.mp4",
"gif_video": "/uploads/videos/653/thumbnail_6P5VDgSGa9dtF0aBZtYI.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/653/240p_FvXJBZj527yxrE8nxVTr.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/653/E05sZTYmZwhqT6FCxabf.mp4",
"title_ar": "فتاة سعودية صغيرة تشير إلى شيء على واجهة المتجر , عائلة سعودية تنظر إلى واجهة المتجر في المول ",
"title_en": "A little Saudi girl points to something on the storefront, a Saudi family looks at the storefront in the mall",
"type": "4K",
"duration": "00:06",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:10:21",
"status": "active",
"token_id": "vAGAa2yXu36BAj35JAJSNIVwiyDCpkyI4pTsgzNs44qgvR6ZyvKKy48YsoYnEYWDn4tXmdOA1c8nTjrAM7lcpxmDlyZGWARMnnM3mxxrTNeI5tKqjxzLLKJb49ft9Ci4BJNBGyphz3FW7IBKjlaNM0KXutWdiRi6DxEV4hNE8cV2SbDFMQtAw0nC01KXtB6MVAqKwCcu",
"extension": "mp4",
"size": "11411395",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "f5a9d38a3bb821b6e63600329b9c6ea8",
"attribution_required": null,
"original_name": "12",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "فتاة سعودية صغيرة تشير إلى شيء على واجهة المتجر , عائلة سعودية تنظر إلى واجهة المتجر في المول ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/653/thumbnail_2Z8Eh6EPL7hWum7HBMzh.png",
"is_like": 0,
"str_slug": "a-little-saudi-girl-points-to-something-on-the-storefront-a-saudi-family-looks-at-the-storefront-in-the-mall",
"post_link": "http://www.stock.com/ar/video/653/a-little-saudi-girl-points-to-something-on-the-storefront-a-saudi-family-looks-at-the-storefront-in-the-mall",
"parent": null
},
{
"id": 655,
"sort": 18379,
"parent_id": null,
"thumbnail": "/uploads/videos/655/thumbnail_2XYbTGG4D5LFTlGddrdM.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/655/thumbnail_t3CvSKJC7J1U3IVqMY5Q.mp4",
"gif_video": "/uploads/videos/655/thumbnail_URtKxsq8GqVXlL10tmDk.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/655/240p_77r7yDrdYOnuXYIdPSTS.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/655/qKNiIOq1qsa239d7Y06e.mp4",
"title_ar": "إبنه سعودية سعيدة  تتسوق مع الأهل في المتجر ، تختار حذاء رياضي",
"title_en": "His happy Saudi son is shopping with the parents in the store, she chooses sneakers",
"type": "4K",
"duration": "00:10",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:10:42",
"status": "active",
"token_id": "Hyl5u03I2n1H6SEpY1Ivnms12ooXGT1jNaYkATooKSqlD0ZzTWa898EheO4qhj2fhBLfeS2xSw7ALSi2OqqzjY3LcYZU7zDL6UcK2huefvofwPIQIRcbrjIzTxyeO7OjCCwCx211Ns64Lhy2kTjJrRCVPW9FV1qMjsqLRl4lyWGtVtI1JgTXg1sURFXJ903G8caaIi2r",
"extension": "mp4",
"size": "16451293",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "ca659c3ffc203c2cb9913c9937c061b1",
"attribution_required": null,
"original_name": "03",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "إبنه سعودية سعيدة  تتسوق مع الأهل في المتجر ، تختار حذاء رياضي",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/655/thumbnail_2XYbTGG4D5LFTlGddrdM.png",
"is_like": 0,
"str_slug": "his-happy-saudi-son-is-shopping-with-the-parents-in-the-store-she-chooses-sneakers",
"post_link": "http://www.stock.com/ar/video/655/his-happy-saudi-son-is-shopping-with-the-parents-in-the-store-she-chooses-sneakers",
"parent": null
},
{
"id": 658,
"sort": 19150,
"parent_id": null,
"thumbnail": "/uploads/videos/658/thumbnail_b6yNrIRnUvOxwLtpSnll.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/658/thumbnail_JEyMjvSnugSyFNQig3Fe.mp4",
"gif_video": "/uploads/videos/658/thumbnail_z7QfDsTmVfunEal2Fjlt.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/658/240p_znIhN6WIK3pZRbwh8UBU.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/658/pjBbXosECtQPH96wrzFr.mp4",
"title_ar": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول  ",
"title_en": "A happy Saudi family sits in the dining hall in the mall. A Saudi family talks at the restaurant table in the mall",
"type": "4K",
"duration": "00:04",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:10:49",
"status": "active",
"token_id": "JIygx4pecU67sGvZjKUItsw3I5bemAfpLoN8ir56ALE4KfWbd2y29jOd9RHxEdTMrTGtG0eziKmCfluoJlQ0yuJdJb0ajcjjcEchd5DVb0XJNhIXC6dQwYcxY1BMiqOsWVIbIe4mCrPAuZxlyQOdGz85HW2FuEwESaGLy1dQlfHOu6HNjpQjLKDBPk5Jqv4jxqzzbR7z",
"extension": "mp4",
"size": "7830212",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "9f2d295c7f8d50435f9a7279ce39fa69",
"attribution_required": null,
"original_name": "20",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول  ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/658/thumbnail_b6yNrIRnUvOxwLtpSnll.png",
"is_like": 0,
"str_slug": "a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"post_link": "http://www.stock.com/ar/video/658/a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"parent": null
},
{
"id": 660,
"sort": 7784,
"parent_id": null,
"thumbnail": "/uploads/videos/660/thumbnail_W038el5RjQSco811RxVi.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/660/thumbnail_lbPMoA4CXvhAoGE4V4vJ.mp4",
"gif_video": "/uploads/videos/660/thumbnail_lUrg01WgKyj6esoAMRq1.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/660/240p_sgrTAxPy6IJfbXtNyCRJ.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/660/D8pMzSiAW7vp4wDieMQU.mp4",
"title_ar": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول  ",
"title_en": "A happy Saudi family sits in the dining hall in the mall. A Saudi family talks at the restaurant table in the mall",
"type": "4K",
"duration": "00:08",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:11:04",
"status": "active",
"token_id": "i4lWn5Pyqi4ir296sOoi3jjQ346aXqqL81MQyaNUUwjKxDq3BXBC1TnQxVNUL6c8jA0kb2vvAZRSQm9YWaANmyOzkRRXBxGnNm0Qipr9ezDFWfxtTvRpIgzA3fBYXPd3TQXJ6nQHPlyJ33QmeYFqqPjSJAa5ST4WCA2IVfHVXlEA7d46hC6Yb0hvw2hiPP7MXjTCZ9mL",
"extension": "mp4",
"size": "13576604",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "8eab759cfeba3ed43c5db67d0b28680f",
"attribution_required": null,
"original_name": "18",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول  ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/660/thumbnail_W038el5RjQSco811RxVi.png",
"is_like": 0,
"str_slug": "a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"post_link": "http://www.stock.com/ar/video/660/a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"parent": null
},
{
"id": 662,
"sort": 15539,
"parent_id": null,
"thumbnail": "/uploads/videos/662/thumbnail_EasQc78zzZ9affGnha2o.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/662/thumbnail_alc0GZd5pHehnb1wFRju.mp4",
"gif_video": "/uploads/videos/662/thumbnail_L15lB321h1kWiLHL4j7X.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/662/240p_xoU3bkrZJLU0WKIwrYMd.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/662/9kWreY1c1kLkj8zd6qDx.mp4",
"title_ar": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول  ",
"title_en": "A happy Saudi family sits in the dining hall in the mall. A Saudi family talks at the restaurant table in the mall",
"type": "4K",
"duration": "00:09",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:11:10",
"status": "active",
"token_id": "MhIQwgeWz9l58vX3PRQDw1gaTv6euwosPc6fxrM5OhohaeDJ4mxpPaw8RFUB30dsDEKhpIcA2zyUFj1uDPHIa9MnrJnBALRZwD6P03ovMHAarJ18kl4DprevWGsfVkZwpyrilK5PLZMKLox8iSdR7FQhNxloCSfi9IMvzMkeNL2C87FoK96LdYkEL034znfy76reLWIQ",
"extension": "mp4",
"size": "15462337",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "085971a47e7f2793b4fe60cd31b7bbb0",
"attribution_required": null,
"original_name": "21",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول  ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/662/thumbnail_EasQc78zzZ9affGnha2o.png",
"is_like": 0,
"str_slug": "a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"post_link": "http://www.stock.com/ar/video/662/a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"parent": null
},
{
"id": 664,
"sort": 5188,
"parent_id": null,
"thumbnail": "/uploads/videos/664/thumbnail_kajSubG4YBSQWEJe7SfE.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/664/thumbnail_vhYcC2V9197wuxuilYe0.mp4",
"gif_video": "/uploads/videos/664/thumbnail_QYNtBukVpz1q7w920CWo.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/664/240p_Dmhq1K4fZryzr1Fu16hB.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/664/vuISNFnkTXO4bDP6iwDc.mp4",
"title_ar": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول ",
"title_en": "A happy Saudi family sits in the dining hall in the mall. A Saudi family talks at the restaurant table in the mall",
"type": "4K",
"duration": "00:07",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:11:15",
"status": "active",
"token_id": "a3OBujSpACMLEHOMxFQb8uFSSrayyJ9I09yv7NMCGIG8GApEkJlEhCgsGa4vkbwDnCREK3vAYGEvHkxwhtLNwAo8Pr1xCgJAczojNyhnkLObSUUCxRWRx6d10gmxPoh27qlte5Vyq9e6JC5dmVi00So9IX1vBsCkl9LOswRuLauXtdYGMVarRVu6TBBZITcCyIrNAPLu",
"extension": "mp4",
"size": "12017400",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "b47a90898693361a3b0820959eed3f3b",
"attribution_required": null,
"original_name": "24",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/664/thumbnail_kajSubG4YBSQWEJe7SfE.png",
"is_like": 0,
"str_slug": "a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"post_link": "http://www.stock.com/ar/video/664/a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"parent": null
},
{
"id": 668,
"sort": 8863,
"parent_id": null,
"thumbnail": "/uploads/videos/668/thumbnail_1X5jS2jmQ7D9akhaiuEl.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/668/thumbnail_PER83GNydelteX2YESWV.mp4",
"gif_video": "/uploads/videos/668/thumbnail_sn3rZJQdgWJv8GMJPFp3.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/668/240p_tWoveutsOauNLPZmeeuH.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/668/Buhzm6mEL72AZ4XKyYd5.mp4",
"title_ar": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول ",
"title_en": "A happy Saudi family sits in the dining hall in the mall. A Saudi family talks at the restaurant table in the mall",
"type": "4K",
"duration": "00:07",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:11:24",
"status": "active",
"token_id": "YpLQR363TQqOVYD2Izc9bldwe3bNvMDY5mI8rKpvyQ4CFg3aixz8GPZrw7pbwrO3WL7XfxLmGsTp2pagR4Jif6u9DsT7tLxcomZ24DBZFbwyGLV2LBkLzbVQL2bD49hQYWzYYnuIlLrKP5XxKAIlQyrA94N9xAqTDmeOFGly2zBIHAHvyh8y66yJFqFR97QwTBbpHj10",
"extension": "mp4",
"size": "12095097",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "8fd38c641799ee00d49014304d95c418",
"attribution_required": null,
"original_name": "23",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "عائلة سعودية سعيدة تجلس في ردهة المطاعم في المول , عائلة سعودية يتحدثان في طاولة المطاعم في المول ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/668/thumbnail_1X5jS2jmQ7D9akhaiuEl.png",
"is_like": 0,
"str_slug": "a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"post_link": "http://www.stock.com/ar/video/668/a-happy-saudi-family-sits-in-the-dining-hall-in-the-mall-a-saudi-family-talks-at-the-restaurant-table-in-the-mall",
"parent": null
},
{
"id": 669,
"sort": 17312,
"parent_id": null,
"thumbnail": "/uploads/videos/669/thumbnail_5J7yHrKlj5a6d0TToijI.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/669/thumbnail_3wRkIA6S3efSBIC3UvP7.mp4",
"gif_video": "/uploads/videos/669/thumbnail_JGY0iJmfkHs4ZY99NUsF.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/669/240p_Z1dHoxjjXA7mu6EYY3v7.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/669/FEYRw4cFybtuqNWt15Qk.mp4",
"title_ar": "أسرة سعودية سعيده مع أكياس التسوق في المركز  التجاري , عائلة سعودية سعيدة تخرج من متجر الملابس , عائلة تتسوق في المول ",
"title_en": "A happy Saudi family with shopping bags in the mall. A happy Saudi family leaves the clothing store. A family shopping in the mall",
"type": "4K",
"duration": "00:09",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:11:24",
"status": "active",
"token_id": "L5xUzARnfM6D8f5AYuQpZeuXqAZnwuVgmQXvj1XGd3RtxyDk46Af0IzCKlqMkcG4koOVcGdEfCHNqo4bbyS3WMsu0iQa1zMv1sOM2c0GG7WQbnwrGHhq208GhMs7fzLsEgVCyAMQo9dkeLIFPLM6GDj3cDbKjgO39I1jRrIX0SzdHxHbVVRvIaPNchnRIrDm1D5hMuTF",
"extension": "mp4",
"size": "14237655",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "07505798a4e066fcd815ec0423736cac",
"attribution_required": null,
"original_name": "19",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "أسرة سعودية سعيده مع أكياس التسوق في المركز  التجاري , عائلة سعودية سعيدة تخرج من متجر الملابس , عائلة تتسوق في المول ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/669/thumbnail_5J7yHrKlj5a6d0TToijI.png",
"is_like": 0,
"str_slug": "a-happy-saudi-family-with-shopping-bags-in-the-mall-a-happy-saudi-family-leaves-the-clothing-store-a-family-shopping-in-the-mall",
"post_link": "http://www.stock.com/ar/video/669/a-happy-saudi-family-with-shopping-bags-in-the-mall-a-happy-saudi-family-leaves-the-clothing-store-a-family-shopping-in-the-mall",
"parent": null
},
{
"id": 670,
"sort": 19970,
"parent_id": null,
"thumbnail": "/uploads/videos/670/thumbnail_grR57RfrGBF9qFCajrEZ.png",
"thumbnail_width": 720,
"thumbnail_height": 406,
"cut_video": "/uploads/videos/670/thumbnail_vkLK6VbqghGy1MLqFSu9.mp4",
"gif_video": "/uploads/videos/670/thumbnail_VMtivo1CLvNOhb4nNRIG.gif",
"gif_video_width": 300,
"gif_video_height": 168,
"size_240p": "/uploads/videos/670/240p_RTJw1n5wZ3o8xcgSg3qd.mp4",
"size_240p_width": 426,
"size_240p_height": 240,
"video_fail": 0,
"price": 170,
"preview": "/uploads/videos/670/f1kZBcPZV4vzG46DpAsI.mp4",
"title_ar": "أسرة سعودية سعيده مع أكياس التسوق في المركز  التجاري , عائلة سعودية سعيدة تخرج من متجر الملابس , عائلة تتسوق في المول ",
"title_en": "A happy Saudi family with shopping bags in the mall. A happy Saudi family leaves the clothing store. A family shopping in the mall",
"type": "4K",
"duration": "00:09",
"description_ar": "",
"description_en": "",
"categories_id": null,
"user_id": 2,
"date": "2020-05-13 18:11:26",
"status": "active",
"token_id": "MFU7zxRCp5WwuaOwmqGd9e2ubQc7nBsF6vZ8CqofFODMOctN52ON9YF0cPlO0qymmDrHllKPYWTjpTpEegQi7dZCI6LAPr24ZUBEBykmTcxQHTIdXWRBeNfPT1Askv4qsYw5X3vlG4UbQ5AnnYV6EPnqZ816LCoK2BsvGNR1yTU7fgCfei5ZIUU4c8QwHgm8hzQpoasn",
"extension": "mp4",
"size": "15261595",
"width": "3840",
"height": "2160",
"aspect_ratio": "0:1",
"fps": 30,
"how_use_image": null,
"stage_edit": 2,
"category_admin_id": 0,
"hash": "2c37c514a06f82e7a84355445e3fc570",
"attribution_required": null,
"original_name": "25",
"category_video_admin_id": null,
"is_uploaded": 1,
"deleted_at": null,
"count_view": 0,
"tags": null,
"title": "أسرة سعودية سعيده مع أكياس التسوق في المركز  التجاري , عائلة سعودية سعيدة تخرج من متجر الملابس , عائلة تتسوق في المول ",
"description": "",
"user": {
"id": 2,
"username": "alaa",
"name": "alaa Sami",
"bio": "",
"country_id": 5,
"city_id": null,
"email": "admin@video.com",
"date": "2019-03-11 13:39:51",
"avatar": "default.jpg",
"cover": "cover.jpg",
"status": "active",
"type_account": "1",
"role": "admin_video",
"website": "",
"twitter": "",
"facebook": "",
"google": "",
"paypal_account": "",
"activation_code": "",
"oauth_uid": "",
"oauth_provider": "",
"token": "Ci4bw5b3tjzcHcj27neX5NVX252YLJ9fyfGYahy55bPSKLrppsDnTHXaqqKac8zrTbRPXULR0Mx",
"authorized_to_upload": "yes",
"instagram": "",
"braintree_id": null,
"paypal_email": null,
"card_brand": null,
"card_last_four": null,
"trial_ends_at": null,
"created_at": null,
"updated_at": null,
"deleted_at": null
},
"thumbnail_resize": "/videos/670/thumbnail_grR57RfrGBF9qFCajrEZ.png",
"is_like": 0,
"str_slug": "a-happy-saudi-family-with-shopping-bags-in-the-mall-a-happy-saudi-family-leaves-the-clothing-store-a-family-shopping-in-the-mall",
"post_link": "http://www.stock.com/ar/video/670/a-happy-saudi-family-with-shopping-bags-in-the-mall-a-happy-saudi-family-leaves-the-clothing-store-a-family-shopping-in-the-mall",
"parent": null
}
]
'));
         $simler_images = $simler_images->take(6);
        if (Auth::check() && $response->user_id != Auth::user()->id && $response->status == 'pending' && Auth::user()->role != 'admin') {
            abort(404);
        } else {
            if (Auth::guest() && $response->status == 'pending') {
                abort(404);
            }
        }

        $uri = $this->request->path();

        if ($response->str_slug == '') {

            $slugUrl = '';
        } else {
            $slugUrl = '/' . $response->str_slug;
        }

        $url_image = 'video/' . $response->id . $slugUrl;

        //<<<-- * Redirect the user real page * -->>>
        $uriImage = str_replace(['ar/','en/'],[''],$this->request->path());
        $uriCanonical = $url_image;

        // if ($uriImage != $uriCanonical) {
        //     return redirect($uriCanonical);
        // }

        //<--------- * VisitImage * ---------->
        $user_IP = request()->ip();
        $date = time();

        if (Auth::check()) {
            // SELECT IF YOU REGISTERED AND VISITED THE PUBLICATION
            $visitCheckUser = $response->visits()->where('user_id', Auth::user()->id)->first();

            if (!$visitCheckUser && Auth::user()->id != $response->user->id) {
                $visit = new VisitVideo;
                $visit->video_id = $response->id;
                $visit->user_id = Auth::user()->id;
                $visit->ip = $user_IP;
                $visit->save();
            }

        } else {

            // IF YOU SELECT "UNREGISTERED" ALREADY VISITED THE PUBLICATION
            $visitCheckGuest = $response->visits()->where('user_id', 0)
                ->where('ip', $user_IP)
                ->orderBy('date', 'desc')
                ->first();

            if ($visitCheckGuest) {
                $dateGuest = strtotime($visitCheckGuest->date) + (7200); // 2 Hours

            }

            if (empty($visitCheckGuest->ip)) {
                $visit = new VisitVideo;
                $visit->video_id = $response->id;
                $visit->user_id = 0;
                $visit->ip = $user_IP;
                $visit->save();
            } else {
                if ($dateGuest < $date) {
                    $visit = new VisitVideo;
                    $visit->video_id = $response->id;
                    $visit->user_id = 0;
                    $visit->ip = $user_IP;
                    $visit->save();
                }
            }

        }//<--------- * VisitImage * ---------->

        $simler_video = $simler_images;
        $child_ids = $response->child->pluck('id');
        $video_in_cart_ids = CartVideo::where(['user_id'  => Auth::id()])->whereIn('video_id',$child_ids)->pluck('video_id')->toArray();

        $exists_in_download = OrderItemsVideo::where(['user_id'  => Auth::id()])->whereIn('video_id',$child_ids)->pluck('video_id')->toArray();

        $tags_chunk = $response
            ->tags()
            ->where('local', app()->getLocale())
            ->pluck('tag')->toArray();

        $response->count_view = $response->count_view + 1;
        $response->save();

        return view('static_html.videos.show', compact('response','video_in_cart_ids','simler_video','tags_chunk','tags'));

    }
}
