<?php

return [
    'landPage' => 'homepage',
    'video.show' => 'productDetail',
    'photo.show' => 'productDetail',
    'vector.show' => 'productDetail',
    'category.show' => 'category',
    'vectors.category.show' => 'category',
    'vectors.category.show' => 'category',
    'search' => 'searchResults',
    'video.search' => 'searchResults',
    'vectors.search' => 'searchResults',
    'user.profile' => 'accountCenter',
    'account.profile' => 'accountCenter',
    'profile.followers' => 'accountCenter',
    'profile.following' => 'accountCenter',
    'account.password' => 'accountCenter',
    'me.collections' => 'accountCenter',
    'me.collections.videos' => 'accountCenter',
    'me.collections.vectors' => 'accountCenter',
    'account.likes' => 'accountCenter',
    'me.plans' => 'accountCenter',
    'me.plans_vector' => 'accountCenter',
    'me.plans_video' => 'accountCenter',
    'me.images' => 'accountCenter',
    'me.videos' => 'accountCenter',
    'me.invoices' => 'accountCenter',
    'me.vectors' => 'accountCenter',
    'photos.home' => 'department',
    'video.home' => 'department',
    'vectors.home' => 'department',
    'categories' => 'department',
    'video.categories' => 'department',
    'vectors.categories' => 'department',
    'category.show' => 'category',
    'video.category.show' => 'category',
    'vectors.category.show' => 'category',
    'search' => 'searchResults',
    'video.search' => 'searchResults',
    'vectors.search' => 'searchResults',
    'plans' => 'propertyDetail',
    'video.plans' => 'propertyDetail',
    'vectors.subscribe_vector' => 'propertyDetail',
];
